spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/mixfruit
    username: root
    password: Password@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  output:
  ansi:
    enabled: DETECT

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
    level:
      org.springframework.web: ERROR
      com.lashan.crudtesting: DEBUG
      org.hibernate: ERROR
  file:
    name: app.log
  logback:
    rollingpolicy:
      max-file-size: 10MB

